# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0002_auto_20171128_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radar',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='ship',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'default_permissions': ()},
        ),
    ]
