# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0003_auto_20171128_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDefenceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='船名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('radius', models.FloatField(verbose_name='防御半径')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShipRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysadmin.Ship')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
