# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0004_shipdefencearea_shiproute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'default_permissions': (), 'permissions': (('can_create_ship', '创建船只'),)},
        ),
    ]
