# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100, unique=True, verbose_name='雷达编号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='雷达名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100, unique=True, verbose_name='船只编号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='船名')),
                ('harbor', models.CharField(default='', max_length=100, verbose_name='码头')),
                ('caption', models.CharField(default='', max_length=100, verbose_name='船长')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='电话')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
            ],
            options={
                'permissions': (('can_create_ship', '创建船只'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShipDefenceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='船名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('radius', models.FloatField(verbose_name='防御半径')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShipRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Ship')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
